
const apartments =
	[
		{
			id: 1,
			apartmentNumber: "C77",
			floor: 3,
			buldingWing: "C",
			area: 29.68,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-C72_C77.jpg",
			apartmentImg: "./images/apartments-plans/apartment/3.png",
		},
		{
			id: 2,
			apartmentNumber: "A11",
			floor: 2,
			buldingWing: "A",
			area: 33.41,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-A11.jpg",
			apartmentImg: "./images/apartments-plans/apartment/2.png",
		},
		{
			id: 7,
			apartmentNumber: "C73",
			floor: 3,
			buldingWing: "C",
			area: 45.73,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-C73_C76.jpg",
			apartmentImg: "./images/apartments-plans/apartment/1.png",
		},
		{
			id: 3,
			apartmentNumber: "C71",
			floor: 3,
			buldingWing: "C",
			area: 49.64,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-C71_C78-1.jpg",
			apartmentImg: "./images/apartments-plans/apartment/1.png",
		},
		{
			id: 4,
			apartmentNumber: "A26",
			floor: 2,
			buldingWing: "A",
			area: 52.60,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-A25_-A26.jpg",
			apartmentImg: "./images/apartments-plans/apartment/1.png",
		},
		{
			id: 5,
			apartmentNumber: "C63",
			floor: 2,
			buldingWing: "C",
			area: 54.82,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-C63.jpg",
			apartmentImg: "./images/apartments-plans/apartment/4.png",
		},
		{
			id: 6,
			apartmentNumber: "C56",
			floor: 2,
			buldingWing: "C",
			area: 82.41,
			status: "Available",
			planImg: "./images/apartments-plans/large-Stan-A23_C56.jpg",
			apartmentImg: "./images/apartments-plans/apartment/5.png",
		},
	];
const data = JSON.stringify(apartments);
export default data;